# Generated by Django 5.2.16 on 2026-07-14 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Job', 'Job'), ('Internship', 'Internship'), ('Learnership', 'Learnership'), ('Bursary', 'Bursary'), ('Scholarship', 'Scholarship'), ('Training', 'Training'), ('Tender', 'Tender'), ('Volunteer', 'Volunteer')], max_length=30)),
                ('location', models.CharField(max_length=200)),
                ('closing_date', models.DateField()),
                ('apply_link', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='opportunities/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
